name: shopping_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  dots_indicator: ^4.0.1
  cached_network_image: ^3.4.1
  get: ^4.7.2
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  # email_validator: ^2.1.17
  shared_preferences: ^2.5.3
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  like_button: ^2.1.0
  flutter_3d_controller: ^2.2.0
  flutter_cache_manager: ^3.4.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/3D/
    - assets/images/
